# Generated by Django 5.0.7 on 2024-08-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_ticket_options_alter_flight_airplane"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="seats_in_rows",
            new_name="seats_in_row",
        ),
    ]
