# Generated by Django 5.0.7 on 2024-08-09 14:51

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_rename_seats_in_rows_airplane_seats_in_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_path
            ),
        ),
    ]
