# Generated by Django 5.0.7 on 2024-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_airplane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
